ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER DDUKDDAK IDENTIFIED BY DDUKDDAK1234;

GRANT RESOURCE, CONNECT TO DDUKDDAK;

ALTER USER DDUKDDAK DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;
