SELECT * FROM MEMBER;

SELECT * FROM PARTNER;

SELECT * FROM PARTNER_TYPE;

INSERT INTO PARTNER VALUES (SEQ_PARTNER_NO.NEXTVAL, 'sh', 1234, '010-1111-2222', 'sh', '홍샘', 12345678, 1);

COMMIT;

SELECT * FROM BIG_CATEGORY;


SELECT PARTNER_NO, PARTNER_ID, PARTNER_PW, PARTNER_TEL, PARTNER_BUSINESS_NAME, PARTNER_CEO_NAME, PARTNER_BUSINESS_NUM, PARTNER_TYPE FROM PARTNER;

SELECT MEMBER_NO, MEMBER_ID, MEMBER_EMAIL, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_TEL, MEMBER_ADDR, MEMBER_POINT, PROFILE_IMG, ENROLL_DATE, MEMBER_DEL_FL, AUTHORITY, SOCIAL_LOGIN_TYPE FROM "MEMBER";

ALTER TABLE MEMBER RENAME COLUMN MEBMER_ADDR TO MEMBER_ADDR;

COMMIT;

SELECT * FROM COMMUNITY;


SELECT * FROM UPLOAD_FILE;

SELECT UPLOAD_IMG_PATH, UPLOAD_IMG_OG_NAME, UPLOAD_IMG_RENAME, UPLOAD_IMG_ORDER, CATEGORY
		FROM UPLOAD_FILE
		WHERE CATEGORY = 5
		ORDER BY UPLOAD_IMG_ORDER;


INSERT INTO UPLOAD_FILE VALUES (SEQ_UPLOAD_IMG_NO.NEXTVAL, '/images/board/', 'boardMainAd.png', 'boardMainAd.png', 1, 5, NULL, NULL, NULL, NULL);
INSERT INTO UPLOAD_FILE VALUES (SEQ_UPLOAD_IMG_NO.NEXTVAL, '/images/board/', 'boardMainAd2.png', 'boardMainAd2.png', 1, 5, NULL, NULL, NULL, NULL);
INSERT INTO UPLOAD_FILE VALUES (SEQ_UPLOAD_IMG_NO.NEXTVAL, '/images/board/', 'boardMainAd3.jpg', 'boardMainAd3.jpg', 1, 5, NULL, NULL, NULL, NULL);
INSERT INTO UPLOAD_FILE VALUES (SEQ_UPLOAD_IMG_NO.NEXTVAL, '/images/board/', 'boardMainAd4.jpg', 'boardMainAd4.jpg', 1, 5, NULL, NULL, NULL, NULL);
INSERT INTO UPLOAD_FILE VALUES (SEQ_UPLOAD_IMG_NO.NEXTVAL, '/images/board/', 'boardMainAd5.jpg', 'boardMainAd5.jpg', 1, 5, NULL, NULL, NULL, NULL);
INSERT INTO UPLOAD_FILE VALUES (SEQ_UPLOAD_IMG_NO.NEXTVAL, '/images/board/', 'boardMainAd6.png', 'boardMainAd6.png', 1, 5, NULL, NULL, NULL, NULL);

SELECT * FROM BOARD_TYPE;
SELECT * FROM COMMUNITY;

SELECT * FROM MEMBER;

SELECT BOARD_NO, BOARD_TITLE, BOARD_CONTENT, READ_COUNT, MEMBER_NO, MEMBER_ID, MEMBER_NICKNAME, UPLOAD_IMG_PATH || UPLOAD_IMG_RENAME AS THUMBNAIL, BOARD_CODE FROM COMMUNITY JOIN MEMBER USING(MEMBER_NO) JOIN UPLOAD_FILE USING(BOARD_NO) WHERE UPLOAD_IMG_ORDER = 0 AND MEMBER_DEL_FL = 'N'ORDER BY BOARD_WRITE_DATE;

SELECT COUNT(*) FROM BOARD_LIKE WHERE BOARD_NO = 1;