SELECT * FROM MEMBER;

SELECT * FROM PARTNER;

SELECT * FROM PARTNER_TYPE;

INSERT INTO PARTNER VALUES (SEQ_PARTNER_NO.NEXTVAL, 'sh', 1234, '010-1111-2222', 'sh', '홍샘', 12345678, 1);

COMMIT;

SELECT * FROM BIG_CATEGORY;


SELECT PARTNER_NO, PARTNER_ID, PARTNER_PW, PARTNER_TEL, PARTNER_BUSINESS_NAME, PARTNER_CEO_NAME, PARTNER_BUSINESS_NUM, PARTNER_TYPE FROM PARTNER;

SELECT MEMBER_NO, MEMBER_ID, MEMBER_EMAIL, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_TEL, MEMBER_ADDR, MEMBER_POINT, PROFILE_IMG, ENROLL_DATE, MEMBER_DEL_FL, AUTHORITY, SOCIAL_LOGIN_TYPE FROM "MEMBER";

ALTER TABLE MEMBER RENAME COLUMN MEBMER_ADDR TO MEMBER_ADDR;

COMMIT;
